version: '3'
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/home/hibarashi_user/normalized_order_data
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する